### ISSUE TITLE
你好，rtsp client和server性能怎么样，在不同板子的cpu利用率大概是多少呢？

### ISSUE THREAD

**Issue by zjd1988** [dreamflyforever/rtsp_simple#1]

**Comment by dreamflyforever** [comment]
你好 zjd1988，rtsp本身协议不太占用cpu使用率，但是摄像头拿到的数据如果是jpg/yuv/rgb等格式，需要转换为h264这一部分会占用很大的cpu，在rk3588测试大概是占用20%cpu(总共100%，8核)。

**Comment by zjd1988** [comment]
@dreamflyforever 嗯嗯，好的，非常感谢。
